#!/usr/bin/env node

/**
 * Manual Database Initialization Script
 * 
 * Use this when pnpm prisma migrate has issues
 * 
 * Usage: node scripts/init-db.js
 */

const fs = require('fs');
const path = require('path');

// PostgreSQL connection string from .env
const envPath = path.join(__dirname, '../.env');
if (!fs.existsSync(envPath)) {
  console.error('❌ .env file not found. Create it with DATABASE_URL first.');
  process.exit(1);
}

const envContent = fs.readFileSync(envPath, 'utf8');
const dbUrlMatch = envContent.match(/DATABASE_URL="([^"]+)"/);

if (!dbUrlMatch) {
  console.error('❌ DATABASE_URL not found in .env');
  process.exit(1);
}

const databaseUrl = dbUrlMatch[1];
console.log('📦 Database URL:', databaseUrl.replace(/:[^@]+@/, ':***@'));

// Create migrations directory
const migrationsDir = path.join(__dirname, '../prisma/migrations');
if (!fs.existsSync(migrationsDir)) {
  fs.mkdirSync(migrationsDir, { recursive: true });
  console.log('✅ Created migrations directory');
}

// Create initial migration SQL
const timestamp = new Date().getTime();
const migrationDir = path.join(migrationsDir, `${timestamp}_init`);
fs.mkdirSync(migrationDir, { recursive: true });

const migrationSql = `-- CreateTable users
CREATE TABLE "users" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "email" TEXT NOT NULL UNIQUE,
  "name" TEXT,
  "credits" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable dubbing_sessions
CREATE TABLE "dubbing_sessions" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "youtubeUrl" TEXT NOT NULL,
  "videoId" TEXT,
  "title" TEXT,
  "sourceLanguage" TEXT NOT NULL DEFAULT 'en',
  "targetLanguage" TEXT NOT NULL DEFAULT 'am',
  "status" TEXT NOT NULL DEFAULT 'pending',
  "progress" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "completedAt" TIMESTAMP(3),
  CONSTRAINT "dubbing_sessions_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE
);

-- CreateIndex
CREATE INDEX "dubbing_sessions_userId_idx" ON "dubbing_sessions"("userId");

-- CreateTable audio_segments
CREATE TABLE "audio_segments" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "sessionId" TEXT NOT NULL,
  "sequence" INTEGER NOT NULL,
  "sourceText" TEXT,
  "translatedText" TEXT,
  "audioUrl" TEXT,
  "duration" DOUBLE PRECISION,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "audio_segments_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "dubbing_sessions" ("id") ON DELETE CASCADE,
  CONSTRAINT "audio_segments_sessionId_sequence_key" UNIQUE("sessionId", "sequence")
);

-- CreateIndex
CREATE INDEX "audio_segments_sessionId_idx" ON "audio_segments"("sessionId");

-- CreateTable usage
CREATE TABLE "usage" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "sessionId" TEXT,
  "service" TEXT NOT NULL,
  "duration" DOUBLE PRECISION,
  "estimatedCost" DOUBLE PRECISION NOT NULL,
  "actualCost" DOUBLE PRECISION,
  "provider" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "usage_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE,
  CONSTRAINT "usage_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "dubbing_sessions" ("id") ON DELETE SET NULL
);

-- CreateIndex
CREATE INDEX "usage_userId_idx" ON "usage"("userId");
CREATE INDEX "usage_sessionId_idx" ON "usage"("sessionId");
`;

fs.writeFileSync(path.join(migrationDir, 'migration.sql'), migrationSql);
console.log('✅ Created migration.sql');

// Create migration_lock.toml
const lockContent = `# Please do not edit this file manually
# It should be added in your version-control system (i.e. Git)
provider = "postgresql"
`;

fs.writeFileSync(path.join(migrationsDir, 'migration_lock.toml'), lockContent);
console.log('✅ Created migration_lock.toml');

console.log('\n📝 Next steps:');
console.log('1. Install Prisma CLI: npm install -g @prisma/cli');
console.log('2. Or use: pnpm exec prisma migrate deploy');
console.log('3. Verify: pnpm exec prisma studio');
